import sys


f = open("wifi.py", "w")

# content
f.write("import os")
f.write("\n")
f.write("\n")
f.write("def createNewConnection(name, SSID, password):")
f.write("\n")
f.write('    config = """<?xml version=\"1.0\"?>')
f.write("\n")
f.write('<WLANProfile xmlns="http://www.microsoft.com/networking/WLAN/profile/v1">')
f.write("\n")
f.write('	<name>"""+name+"""</name>')
f.write("\n")
f.write('	<SSIDConfig>')
f.write("\n")
f.write('		<SSID>')
f.write("\n")
f.write('			<hex>52345F4F70656E57525432</hex>')
f.write("\n")
f.write('			<name>"""+SSID+"""</name>')
f.write("\n")
f.write('		</SSID>')
f.write("\n")
f.write('		<nonBroadcast>true</nonBroadcast>')
f.write("\n")
f.write('	</SSIDConfig>')
f.write("\n")
f.write('	<connectionType>ESS</connectionType>')
f.write("\n")
f.write('	<connectionMode>auto</connectionMode>')
f.write("\n")
f.write('	<MSM>')
f.write("\n")
f.write('		<security>')
f.write("\n")
f.write('			<authEncryption>')
f.write("\n")
f.write('				<authentication>WPA2PSK</authentication>')
f.write("\n")
f.write('				<encryption>AES</encryption>')
f.write("\n")
f.write('				<useOneX>false</useOneX>')
f.write("\n")
f.write('			</authEncryption>')
f.write("\n")
f.write('			<sharedKey>')
f.write("\n")
f.write('				<keyType>passPhrase</keyType>')
f.write("\n")
f.write('				<protected>false</protected>')
f.write("\n")
f.write('				<keyMaterial>"""+password+"""</keyMaterial>')
f.write("\n")
f.write('			</sharedKey>')
f.write("\n")
f.write('		</security>')
f.write("\n")
f.write('	</MSM>')
f.write("\n")
f.write('</WLANProfile>"""')
f.write("\n")
f.write('    command = "netsh wlan add profile filename=\\""+name+".xml\\""+" interface=')
f.write(sys.argv[3])
f.write('"')
f.write("\n")
f.write('    with open(name+".xml", "w") as file:')
f.write("\n")
f.write('        file.write(config)')
f.write("\n")
f.write('    os.system(command)')
f.write("\n")

f.write("\n")
f.write('# function to connect to a network')
f.write("\n")

f.write('def connect(name, SSID):')
f.write("\n")
f.write('    command = "netsh wlan connect name=\\"')
f.write('"')
f.write('+name +')
f.write(" \\")
f.write("\n")
f.write('        "\\" ssid=\\""+SSID+"\\" interface=')
f.write(sys.argv[3])
f.write('"')
f.write("\n")
f.write('    os.system(command)')
f.write("\n")

f.write("\n")
f.write('# function to display avavilabe Wifi networks')
f.write("\n")
f.write("\n")

f.write('def displayAvailableNetworks():')
f.write("\n")
f.write('    command = "netsh wlan show networks interface=')
f.write(sys.argv[3])
f.write('"')
f.write("\n")
f.write('    os.system(command)')
f.write("\n")

f.write("\n")
f.write('# display available netwroks')
f.write("\n")
f.write("\n")

f.write('displayAvailableNetworks()')
f.write("\n")

f.write("\n")
f.write('# input wifi name and password')
f.write("\n")
f.write("\n")


f.write("name = ")
f.write("'")
f.write(sys.argv[1])
f.write("'")
f.write("\n")
f.write("password = ")
f.write("'")
f.write(sys.argv[2])
f.write("'")
f.write("\n")

f.write("\n")
f.write('# establish new connection')
f.write("\n")

f.write('createNewConnection(name, name, password)')
f.write("\n")
f.write("\n")

f.write("\n")
f.write('# connect to the wifi network')
f.write("\n")
f.write("\n")

f.write('connect(name, name)')
f.write("\n")
f.write('print("If you arent connected to this network, try connecting with the correct password!")')

f.close()
